### ISSUE TITLE
Update map stroke and fill

### ISSUE THREAD

**Issue by ppscvalentin** [ogorlab/ogor-frontend#142]
For map with raster images:
![image](https://user-images.githubusercontent.com/4716271/86333496-a6cdc780-bc54-11ea-83a7-e8ebe44a38e3.png)

#000 stroke, 1.5 stroke width, fill #969792 with 60% opacity for no data

For map with average NDVI:
It's perfect the way it is 👍

**Comment by alexkiro** [comment]
Discussed today, we will not use the fill under rasters as that's not currently supported by GMaps
