### ISSUE TITLE
Move the hover info cards on top of the parcel

### ISSUE THREAD

**Issue by alexkiro** [ogorlab/ogor-frontend#161]
Instead of placing hover cards in the corner of the screen as we do now, we should instead hover them on top of the parcel. Using the representative points returned by the backend (https://github.com/ogorlab/ogor-backend/issues/330)

**Comment by ppscvalentin** [comment]
![image](https://user-images.githubusercontent.com/4716271/88559677-caa6e200-d035-11ea-806b-1aabef8a5917.png)
