### ISSUE TITLE
Add history tab to the observation map view

### ISSUE THREAD

**Issue by alexkiro** [ogorlab/ogor-frontend#162]
Currently the observation "tab" is just a link to the regular history page, instead of that, it will be more useful to have the quick access history tab in it's place.

---

Mocks not yet finalized.

**Comment by ppscvalentin** [comment]
![image](https://user-images.githubusercontent.com/4716271/88539271-9e7d6800-d019-11ea-85f2-5885e1de17b1.png)
Mocks have been finalised :)
