### ISSUE TITLE
Show true color thumbnail in the map view

### ISSUE THREAD

**Issue by alexkiro** [ogorlab/ogor-frontend#163]
Detail still need to be clarified.

**Comment by ppscvalentin** [comment]
![image](https://user-images.githubusercontent.com/4716271/88538710-80633800-d018-11ea-8904-e0a0cd9cbba9.png)

This is the true color thumbnail. It would be nice to toggle it in the map layer, but I understand we don't the image at that big of a resolution.

This thumbnail also opens a menu to choose between different map layers. It looks like this:

![image](https://user-images.githubusercontent.com/4716271/88538906-dd5eee00-d018-11ea-88b2-e2537fda1a98.png)

**Comment by alexkiro** [comment]
> It would be nice to toggle it in the map layer, but I understand we don't the image at that big of a resolution.

IIUC @ppscvalentin that can be done, however there will be (high) additional storage costs. You'll probably need to bring that up discussion up at the next meeting if you want that decision change.

**Comment by alexkiro** [comment]
This seems to be tied to the design for #171 waiting for the design there to be finished.
