### ISSUE TITLE
Add the ability to switch between NDWI and NDVI raster types

### ISSUE THREAD

**Issue by alexkiro** [ogorlab/ogor-frontend#171]
A global select component is displayed in most of the main views that allows the user to switch between NDWI / NDVI:

---

Views:

 - [x] Grid view
 - [x] Parcel History 
 - [x] Map view
 - [x] Map view, observation details 

---

Additionally:

 - [x] Compare parcels view should use the same raster type as selected
 - [x] Compare observation view should use the same raster type as selected
 - [x] Whenever the viewed type changes the data is reloaded with the new content 
 - [x] The URL should reflect the observation type

**Comment by ppscvalentin** [comment]
Related to: https://github.com/ogorlab/ogor-frontend/issues/163

You can also toggle between NDVI and NDWI from the (simple) select box in the navbar:
![image](https://user-images.githubusercontent.com/4716271/88539723-6f1b2b00-d01a-11ea-9d58-25ab0dec530d.png)

**Comment by alexkiro** [comment]
@ppscvalentin I think it would be best to include to include the whole application here as well, i.e. also the map view and the history and the full user workflow. Otherwise it's far too confusing for the user IMO.
