### ISSUE TITLE
STAGING.When selecting fields, the parcels are doubled in the list.

### ISSUE THREAD

**Issue by dafinajeaca** [ogorlab/ogor-frontend#172]
The selected parcels should be removed from the available list of parcels.

![Screenshot-2020-07-20T11_00_16 540Z](https://user-images.githubusercontent.com/52447572/87930944-9e1d2400-ca91-11ea-8c46-3ed968480c4d.png)

**Comment by alexkiro** [comment]
Updated on staging to stop duplicated.

---

I do still recommended the information should be duplicated, as I believe having the item disappear when the checkbox is selected is much more confusing.
