### ISSUE TITLE
STAGING.Home button is truncated in the back.

### ISSUE THREAD

**Issue by dafinajeaca** [ogorlab/ogor-frontend#173]
* Select a field
* Press "Selecteaza terenuri"
* The Selection area appears. The home button remains displayed (only half of it) in the background.
TBD: Check with Valentin for a visual solution.

**Comment by dafinajeaca** [comment]
![Screenshot-2020-07-20T11_04_07 675Z](https://user-images.githubusercontent.com/52447572/87931330-4df29180-ca92-11ea-8f76-eb14b0369821.png)

**Comment by alexkiro** [comment]
The button now hides when the search bar opens up.
