### ISSUE TITLE
STAGING.From a selected field, if I change the season date, the selection is lost.

### ISSUE THREAD

**Issue by dafinajeaca** [ogorlab/ogor-frontend#176]
https://www.loom.com/share/04ef6235bff64e66a60b0bcd689bf41c

**Comment by alexkiro** [comment]
@dafinajeaca this is the same issue as in the past. There is no way for us to determine what the equivalent parcel is in a different season, so ATM the map completely resets when a new season is reached to avoid any weirdness. 

---

Are we ok with us "guessing" the equivalent parcel, similar to how we are currently doing in the Parcel History page (we are going to get it wrong a lot)? If we are we can keep the selection between seasons.
