### ISSUE TITLE
Show most recent raster when none is available at the selected date in the grid view

### ISSUE THREAD

**Issue by dafinajeaca** [ogorlab/ogor-frontend#177]
In these cards add the date of the observation, under the field name.
Check with Valentin for the newer mockup version.

**Comment by ppscvalentin** [comment]
![image](https://user-images.githubusercontent.com/4716271/88540547-d2598d00-d01b-11ea-9940-3f30fd2faf9b.png)

+ tooltip on date: 'Imaginea din Jul 30 nu poate fi afișată'

**Comment by ppscvalentin** [comment]
Changed tooltip text

**Comment by ppscvalentin** [comment]
![image](https://user-images.githubusercontent.com/4716271/88561037-903e4480-d037-11ea-9ade-86cd58052e5c.png)

Added 50% opacity on NDVI raster here as well to be consistent with https://github.com/ogorlab/ogor-frontend/issues/178

**Comment by alexkiro** [comment]
After today's standup, it appears more discussion is need putting on hold until that is resolved.
