### ISSUE TITLE
Show most recent raster when none is available at the selected date in the map view

### ISSUE THREAD

**Issue by dafinajeaca** [ogorlab/ogor-frontend#178]
Add the date in the popup info card.
Add the date in the details of the field (if the field is selected)
Check with Valentin for the newer mockup version.

**Comment by ppscvalentin** [comment]
Set NDVI raster image at 50% opacity for past observations, back to 100% on mouse over

![image](https://user-images.githubusercontent.com/4716271/88560352-b44d5600-d036-11ea-9c2d-ef78134df478.png)
![image](https://user-images.githubusercontent.com/4716271/88560370-b9120a00-d036-11ea-9144-19418ef6eb14.png)

**Comment by alexkiro** [comment]
After today's standup, it appears more discussion is need putting on hold until that is resolved.
