### ISSUE TITLE
Add the ability to add fields to an existing season 

### ISSUE THREAD

**Issue by alexkiro** [ogorlab/ogor-frontend#182]
ATM once a season is created other parcels cannot be added to it. We should allow the user to add new batches of parcels to an existing season:

 - [x] Add new import page to manage batches of parcels
 - [x] List existing batches of parcels together with stats about each individual batch
 - [x] Allow creating new batches of parcels from imports 
 - [x] Allow creating new batches of parcels from the APIA scraper
 - [x] Show notice if a season has parcels with undefined crops 
 - [x] When redirecting the user to the map view after a successful import, show a notice explaining that the rasters are not available yet
 - [x] If parcels have geometry errors show a map view with the parcels in the batch, both valid and invalid ones.

**Comment by dafinajeaca** [comment]
OK with production deployment
