### ISSUE TITLE
Share. The shared page should be displayed in the language selected by the farmer.

### ISSUE THREAD

**Issue by dafinajeaca** [ogorlab/ogor-frontend#197]

**Comment by alexkiro** [comment]
Q: What can the anonymous user do if they don't know the language used by the farmer who shared the parcel?

**Comment by dafinajeaca** [comment]
The issue will be closed now, as we have decided that for the next version we will add a language selector to the shared page.

**Comment by alexkiro** [comment]
> The issue will be closed now, as we have decided that for the next version we will add a language selector to the shared page.

Opened follow up tickets: 

  - https://github.com/ogorlab/ogor-frontend/issues/199
  - https://github.com/ogorlab/ogor-frontend/issues/200
