### ISSUE TITLE
Replace ClimateKIC logo with the attached one.

### ISSUE THREAD

**Issue by dafinajeaca** [ogorlab/ogor-frontend#201]
- [ ] Replace logo
- [x] Set also link to www.climate-kic.org 
- [x] Add links to the other logos also
  https://copernicus-incubation.eu/
  https://accelerator.copernicus.eu/
  https://parsec-accelerator.eu/
  https://www.innovationlabs.ro/

**Comment by dafinajeaca** [comment]
![Climate-KIC logo mic](https://user-images.githubusercontent.com/52447572/88903930-14254600-d25d-11ea-84e8-ee5f4eddfad2.png)

**Comment by alexkiro** [comment]
Links have been added.

**Comment by alexkiro** [comment]
Superseded by #220 and #232
