### ISSUE TITLE
Change history button to be a back button in the parcel history view 

### ISSUE THREAD

**Issue by ppscvalentin** [ogorlab/ogor-frontend#211]
If I click on 'See detailed history' in Map view / Field History it sends me to Grid view / Field History. But when I click on 'History', expecting to go back, I end up on Grid view / All fields.

---

 - [x] When moving from the map parcel details view to the parcel history view, the current route parameters should be used the route in the back button
 - [x] When moving from the grid view to the parcel history view, the current route parameters should be used the route in the back button
 - [x] When changing seasons in the parcel history view, the back button should preserve it's original value
 - [x] If the user lands on the parcel history view and no reference to what view should be used as the "back to" view, we should default to the grid view for the current farm (as it is now)

**Comment by alexkiro** [comment]
> If I click on 'See detailed history' in Map view / Field History it sends me to Grid view / Field History. But when I click on 'History', expecting to go back, I end up on Grid view / All fields.

This has not been implemented as a back button, but rather implemented as discussed [here](https://www.figma.com/file/6xsarPsmSjCNVLbN1nBa3C?node-id=3641:436#32991182). Which is a hardcoded link to the grid view.

---

@ppscvalentin If we do want to implement this as a back button, I have a couple of questions:

 1. When going back, do we reset the previous view to it's default state, or try to reproduce the state as best as possible when going back to it? 
 2. If there is no "back to this view" reference, what is the default view should we send the user to?

**Comment by ppscvalentin** [comment]
> When going back, do we reset the previous view to it's default state, or try to reproduce the state as best as possible when going back to it?

Try to reproduce as best as possible.

> If there is no "back to this view" reference, what is the default view should we send the user to?

Defaults to Grid view / All fields.
