### ISSUE TITLE
Change the initial position of the history slider for missing rasters

### ISSUE THREAD

**Issue by alexkiro** [ogorlab/ogor-frontend#222]
Scenario:

 - user is viewing the map view
 - user clicks on a parcel that does not have a raster for the selected date
 - user click on the history tab 

---

ATM the user is put on the start of the season. The desired outcome has yet to be determined.

**Comment by ppscvalentin** [comment]
True. I was on a farm viewing the images for March 11, 2020 -> Clicked the history tab of a field with a missing image -> ended up looking at the image from the start of the season (September 3, 2019). For that particular field there is an image available on March 16, 2020, just 5 days away from the initial image.

In this scenario it would be ideal to focus the history slider on the nearest image, past or future.
