### ISSUE TITLE
Show admins a link to the Census page for a parcel

### ISSUE THREAD

**Issue by mgax** [ogorlab/ogor-frontend#226]
When logged in as admin, and impersonating a farmer, and a parcel is selected, display a link to the Census page for that parcel (https://github.com/ogorlab/ogor-census/issues/53), to make it easy to debug long spans of missing observations.

**Comment by mgax** [comment]
After some discussion, we're not adding the link to the front-end just now, because it needs design work. Census will have a parcel listing of its own, with links to parcels, and hopefully that will be simple enough to navigate.

**Comment by alexkiro** [comment]
I think this is out of date as of https://github.com/ogorlab/ogor-frontend/issues/258
