### ISSUE TITLE
Replace ClimateKIC logo with the one attached.

### ISSUE THREAD

**Issue by dafinajeaca** [ogorlab/ogor-frontend#232]
![White-EIT-Climate-KIC-White-EU-flag-transparent](https://user-images.githubusercontent.com/52447572/89880661-298b6000-dbcd-11ea-8c82-6300d5395ec9.png)

**Comment by alexkiro** [comment]
Need small and large assets for this. As we have [now for current logos](https://github.com/ogorlab/ogor-frontend/tree/master/public/landing/accelerators)

**Comment by ppscvalentin** [comment]
Updated logos: https://drive.google.com/drive/u/4/folders/1vb6hXm7fvPdaP5L_y8heluRjytsyosnl
