### ISSUE TITLE
Update date picker animations

### ISSUE THREAD

**Issue by alexkiro** [ogorlab/ogor-frontend#239]
- [x] Remove smooth scrolling behavior
- [x] Attempt to keep the same "position" when changing years, based on the date the user is currently scrolled at 
- [x] If the month is not present in the year the user move to fallback to the end of the season as we do now.

**Comment by dafinajeaca** [comment]
@ppscvalentin : Please also check this issue.

**Comment by ppscvalentin** [comment]
Works great for most cases. Found one that could use some work:

1. I am in the current, ongoing season and it's 30 July.
2. I want to go back one year and I click on the previos season expecting to be scrolled near July
3. However I end up in December

I suppose it goes at the end of a season.

**Comment by alexkiro** [comment]
> Works great for most cases. Found one that could use some work:

Should be fixed now, you mind trying again.
