### ISSUE TITLE
Add the ability to request access to a farm

### ISSUE THREAD

**Issue by alexkiro** [ogorlab/ogor-frontend#251]
If an user already has access to some 10 or more parcels from a farm, they should be able to request full access from the farmer.

**Comment by dafinajeaca** [comment]
Nu imi apare butonul de request acces la ferma.
![image](https://user-images.githubusercontent.com/52447572/95360061-8e182200-08d3-11eb-8272-c5fceaf57f14.png)

**Comment by dafinajeaca** [comment]
In plus, vad ca la ferma "Ferma mea", unde am primit acces doar la un teren, apar in descriere 54 terenuri, cu 1402.2 ha. Nu ar trebui sa apara doar numarul de terenuri share-uite?

**Comment by alexkiro** [comment]
@dafinajeaca **please use English here.**

---

The button to request access to the entire farm is only displayed after the user receives access to 10 or more parcels. This is what @ppscvalentin requested. It's quite the easy change to update the minimum number of parcels required, so just let me know if we need changes there :smile: 

The statistics of the farm is unrelated to this issue, and it's something that was introduced in https://github.com/ogorlab/ogor-frontend/issues/200. So please open a new issue if that needs changing.

**Comment by alexkiro** [comment]
> The button to request access to the entire farm is only displayed after the user receives access to 10 or more parcels. This is what @ppscvalentin requested. It's quite the easy change to update the minimum number of parcels required, so just let me know if we need changes there

We discussed this at today's standup, everyone agreed we should show the button after 1 parcel has been shared.
