### ISSUE TITLE
Map view when all fields miss data. You cannot see them.

### ISSUE THREAD

**Issue by ppscvalentin** [ogorlab/ogor-frontend#255]
Where you don't see the fields:
![image](https://user-images.githubusercontent.com/4716271/90110750-620a7580-dd56-11ea-86c0-3183fd8e0ce6.png)

Where they are:
![image](https://user-images.githubusercontent.com/4716271/90110818-79e1f980-dd56-11ea-8e9a-0ad383489bf7.png)

**Comment by alexkiro** [comment]
Discussed with @ppscvalentin . He decided against using GitHub issues for his tasks.
