### ISSUE TITLE
Handle really small area sizes

### ISSUE THREAD

**Issue by alexkiro** [ogorlab/ogor-frontend#265]
At the moment we only show 1 decimal point for a parcels area. However we do have some cases where the parcel is so small the number is actually rounded to `0.0`, if the actual size is smaller than `0.005`. We should not be showing `0.0` as that is really confusing.

**Comment by ppscvalentin** [comment]
Would "≤0.1 ha" solve the issue?

**Comment by alexkiro** [comment]
> Would "≤0.1 ha" solve the issue?

I'm afraid you're a bit late to the party. We already implement a different solution here and we will be simply rounding up for this cases instead of down as we are doing now. Feel free to open another issue if you want this changed.
