### ISSUE TITLE
Show preview when pasting link to field

### ISSUE THREAD

**Issue by ppscvalentin** [ogorlab/ogor-frontend#281]
Could we use this image:
![image](https://user-images.githubusercontent.com/4716271/91307896-386e3700-e7b7-11ea-9a31-a1e5d4d4a2db.png)

as preview when we paste links on Slack, Facebook or any messaging service instead of the default cover:
![image](https://user-images.githubusercontent.com/4716271/91308102-7cf9d280-e7b7-11ea-9a4c-fcb2e1531602.png)

**Comment by alexkiro** [comment]
@ppscvalentin this can be done, but it is really involved. Requires us to add static webpages along our existing SPA, and to pre-render all images. 

I would advice against it if our users are not using this feature.

**Comment by ppscvalentin** [comment]
I understand. I don't think it's worth the trouble just for that. I'll just use a generic cover image for now.
