### ISSUE TITLE
Scenario when the field observation page does not display the raster

### ISSUE THREAD

**Issue by dafinajeaca** [ogorlab/ogor-frontend#300]
1. From the farm map view, filter by one crop, let's say wheat.
2. Click on a field with maize.
3. The field observation map details map opens, but raster is not displayed.

Expected: The raster should be displayed.

**Comment by alexkiro** [comment]
So I see a couple of ways of resolving this issue, will need to discuss and decide on one these (or any other ones that I can't think of right now). 

---

When moving to the state of the map view where a parcel is selected:

 1. Reset all map filters. And so both the raster for the selected parcel and all other parcels are now shown.
 2. Force include the raster of the selected parcel. And so all other parcels are still hidden.
 3. Do not allow the user to select a parcel that has been filtered out, so the user cannot run into this issue in the first place.

**Comment by dafinajeaca** [comment]
From the above options, I think that the first one is the best.
@ppscvalentin What do you think?

**Comment by ppscvalentin** [comment]
Sounds good to me if the filters are restored once you deselect the parcel
