### ISSUE TITLE
Add farmer statistics in the staff user view

### ISSUE THREAD

**Issue by dafinajeaca** [ogorlab/ogor-frontend#306]

**Comment by alexkiro** [comment]
@dafinajeaca all farmers start with a farm, and cannot add another one at this point. So this column will be the same for everyone ATM. 

We will probably need another way to determine this?

**Comment by dafinajeaca** [comment]
> @dafinajeaca all farmers start with a farm, and cannot add another one at this point. So this column will be the same for everyone ATM.
> 
> We will probably need another way to determine this?

Maybe no of ha in the current season could be the criteria?
