### ISSUE TITLE
Tracking codes for ogor.ro

### ISSUE THREAD

**Issue by nico4** [ogorlab/ogor-frontend#33]
**Mouseflow**

```
<script type="text/javascript">
    window._mfq = window._mfq || [];
    (function() {
        var mf = document.createElement("script");
        mf.type = "text/javascript"; mf.defer = true;
        mf.src = "//cdn.mouseflow.com/projects/530a3ab0-5517-4f0d-bb5f-1b6d05843061.js";
        document.getElementsByTagName("head")[0].appendChild(mf);
    })();
</script>
```
To install Mouseflow, you need to copy the following script to the end of the <body>-section of each web page you want to record.

SPA: https://support.mouseflow.com/support/solutions/articles/44001508929-single-page-applications

**Google Analytics**

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-160817162-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'UA-160817162-1');
</script>
```
Copy and paste this code as the first item into the <HEAD> of every web page that you want to track.
SPA: https://developers.google.com/analytics/devguides/collection/analyticsjs/single-page-applications

**Comment by nico4** [comment]
Need testing before going live.

**Comment by dafinajeaca** [comment]
All installed and running.
