### ISSUE TITLE
Always save preferred language

### ISSUE THREAD

**Issue by mgax** [ogorlab/ogor-frontend#334]
When sending emails from the backend, the user's preferred language is used, but the backend only receives a preferred language when the user explicitly changes the language (https://github.com/ogorlab/ogor-backend/pull/505#discussion_r490983181).

Should the front-end set the preferred language, when it's not set, based on the current browser preferences?

**Comment by mgax** [comment]
> Should the front-end set the preferred language, when it's not set, based on the current browser preferences?

@dafinajeaca says "yes" :)

**Comment by alexkiro** [comment]
> Should the front-end set the preferred language, when it's not set, based on the current browser preferences?

We agreed at today's meeting to do this.
