### ISSUE TITLE
Account settings page is not accessible. Link Settings does nothing. Nothing, I tell you!

### ISSUE THREAD

**Issue by dafinajeaca** [ogorlab/ogor-frontend#355]
https://www.loom.com/share/02f388ba169f4fb68d2c45f70b710937

**Comment by alexkiro** [comment]
This does work for most users, so will need to see how to replicate this.

**Comment by dafinajeaca** [comment]
> This does work for most users, so will need to see how to replicate this.

Now it works. :)

**Comment by alexkiro** [comment]
> > This does work for most users, so will need to see how to replicate this.
> 
> Now it works. :)

I've taken a quick look, and tried to replicate but with no success. Will close for now .
