### ISSUE TITLE
Landing page - design

### ISSUE THREAD

**Issue by nico4** [ogorlab/ogor-frontend#37]
**CTA: Farmer should provide an email address for us to open an account**

Page **must-have**:

* Value proposition (Always on the field)
* Phone number (0721 223 623)
* Email address (contact@ogor.ro)
* Login
* Main features:
  * Satellite data for your farm from 2017
  * Easy import from APIA
  * Field evolution (by seasons)
  * No input required after
  * Easy to read/understand - no technical background required
* Price: FREE

Page **nice-to-have**:

* Total number of HA
* Used by Arnaud, Olteanu and other big farmers 
* Winners of the Copernicus Incubation, Accelerator, PARSEC, Innovation Labs
* See demo

**Comment by dafinajeaca** [comment]
Design ready and feedback received.
https://www.figma.com/proto/HaJnsZa7RkHjzV1DqODyXu/OGOR-Landing-Page?node-id=1708%3A0&viewport=2560%2C689%2C0.2545723617076874&scaling=scale-down
