### ISSUE TITLE
OGOR share screen

### ISSUE THREAD

**Issue by costinbusioc** [ogorlab/ogor-frontend#38]
@nico4 suggested that at some point, it would be nice to have a share screen feature in OGOR such that farmers can collaborate and advice each other on their cultures.

The initial suggestion was to try Zoom API https://marketplace.zoom.us/docs/guides/tools-resources/zoom-apis, but which looks like doesn't support screen sharing out of the box, but rather enforces the users to have Zoom installed and only allow the developer to create meetings or things like that. Sent an e-mail to their developer support group with no concrete answer for the share screen functionality.

On my research, found two APIs that support screen sharing:

1. https://deadsimplescreensharing.com/screen-sharing-api
- audio/video conference integrated
- free version allows for 4 users/meeting
- works as a pop up in browser
- not much documentation, not sure if what they share as an example is enough to use as the API (my javascript knowledge and power is <<)

2. https://www.screenleap.com/api
- no free version (they allow for 5 hours of free testing in order to see how it works)
- the basic subscription is **0.003$/minute/user** so like 5hours=1$/user. It may be integrated with the OGOR subscription somehow?
- their documentation looks better than the one above (more exampels, FAQ etc)
- IFIK, the browser extension solution works only on Chrome, for other browsers the users may need to download their app (which is not that nice)

Of course, everything I typed/looked an needs to have a look from @alexkiro

**Comment by dafinajeaca** [comment]
Added an entry in the "Features and User Stories" board:
https://github.com/ogorlab/non-tech/issues/94

This one will be closed until the feature is re-started.
