### ISSUE TITLE
Uploading fields with bad geometry. Can't see them on map.

### ISSUE THREAD

**Issue by ppscvalentin** [ogorlab/ogor-frontend#420]
Tried uploading this kml file on dev. It has a field with self-intersection. Should be able to see the field on the map, but I am currently seeing a generic upload error.

**Comment by alexkiro** [comment]
> Tried uploading this kml file on dev. It has a field with self-intersection. Should be able to see the field on the map, but I am currently seeing a generic upload error.

That's because the feature is not ready. It's still a WIP.
