### ISSUE TITLE
Click on padding does not open the sidebar

### ISSUE THREAD

**Issue by alexkiro** [ogorlab/ogor-frontend#425]
When the user clicks on the padding, the sidebar does not open. This is an artifact of the fact that there were multiple design of the sidebar opener at one point. We should attempt to simplify all the messy stuff there. 

![Screenshot from 2020-11-23 08-38-24](https://user-images.githubusercontent.com/1538458/99934685-54a65380-2d67-11eb-8b0b-9b892706b3a8.png)

**Comment by andreighh** [comment]
Do we want the compact version of the sidebar to allow a clickable padding, as well?
![image](https://user-images.githubusercontent.com/61791875/100459698-92400f00-30ce-11eb-948c-22cdb8140914.png)
