### ISSUE TITLE
Landing page 

### ISSUE THREAD

**Issue by alexkiro** [ogorlab/ogor-frontend#44]
Add a static landing page with information about the app, and the ability to request a new account.

 - [x] Add the new page and modify the first page to point to it
 - [x] Add static prerender of the pages for search engines 
   - We have this added, and tested but it's temporarily disabled as we need to figure out where to build with prerender (as we will need Chrome/Chromium)
 - [x] Add the ability for new users to request an account 
 - [x] Add image meta tags for SEO and social media sharing
 - [x] Add description meta tags for SEO and social media sharing
 - [x] Add links to social accounts
 - [x] Add pictures of real people
 - [x] Add responsiveness 

### Extra 

 - ~Add ReCaptcha~ not ATM
 - [ ] Add fancy scrolling behavior for the feature list section.

**Comment by alexkiro** [comment]
> [ ] Add static prerender of the pages for search engines
> * We have this added, and tested but it's temporarily disabled as we need to figure out where to build with prerender (as we will need Chrome/Chromium)

We're moving the build env to Jenkins (see #57)

**Comment by ppscvalentin** [comment]
SEO and social media sharing:
Link to og:image cover: https://drive.google.com/open?id=1AzKGQlOD53V3N7v74FKWFTiQs_kIoFUG

Links to social accounts:
Medium: https://medium.com/@ogor.rocks
LinkedIn: https://www.linkedin.com/company/ogor/
Not using facebook now.

**Comment by ppscvalentin** [comment]
@alexkiro added 96dpi logos for landing page footer in: 
https://drive.google.com/drive/u/4/folders/1vb6hXm7fvPdaP5L_y8heluRjytsyosnl

**Comment by ppscvalentin** [comment]
@alexkiro landing page design has been update:

https://www.figma.com/file/HaJnsZa7RkHjzV1DqODyXu/OGOR-Marketing?node-id=1811%3A204
