### ISSUE TITLE
Deselecting all files for import does not allow reselecting them afterwards

### ISSUE THREAD

**Issue by andreighh** [ogorlab/ogor-frontend#441]
Steps to reproduce:
1. Add parcels, in import
2. Select kml, kmz etc
3. Click upload
4. Select all files in the dialog window
5. Deselect all those files one by one
6. Click upload again and select all four files, it won't work, but selecting only a file and then selecting all of them will work

**Comment by nico4** [comment]
Pare ca nu mege inca sa incarc mai multe fisiere: https://www.loom.com/share/561ea64d2ee24f809d9d8eb8ec6c5755

**Comment by alexkiro** [comment]
> Pare ca nu mege inca sa incarc mai multe fisiere: https://www.loom.com/share/561ea64d2ee24f809d9d8eb8ec6c5755

The only multifile batchfile format currently supported is shapefile which requires 4 different files:

 - shp
 - shx
 - dbf
 - prj
