### ISSUE TITLE
New view: Crops overview

### ISSUE THREAD

**Issue by ppscvalentin** [ogorlab/ogor-frontend#450]
![image](https://user-images.githubusercontent.com/4716271/101325335-3dda2380-3874-11eb-86f9-894b998534c9.png)

- This view is accessible from sidebar.
- It becomes the new homepage
- Sorted by surface
- The red warnings signify "fields with problem" (i.e. below average NDVI of that crop) cc: @nico4 can you please open a ticket for that?

Ref: https://github.com/ogorlab/non-tech/issues/126 (reports)

**Comment by ppscvalentin** [comment]
![image](https://user-images.githubusercontent.com/4716271/101343284-738b0680-388c-11eb-90b6-d0a958be31ab.png)

**Comment by mgax** [comment]
On Firefox, Mac OS, I'm seeing a bunch of scroll bars (screenshot from staging):

<img width="1250" alt="Screenshot 2020-12-24 at 10 48 09" src="https://user-images.githubusercontent.com/27617/103076094-a267e300-45d5-11eb-926c-2c15a0d36ba7.png">

**Comment by nico4** [comment]
Arată bine în rest.

**Comment by alexkiro** [comment]
> On Firefox, Mac OS, I'm seeing a bunch of scroll bars (screenshot from staging):

That's because of the impersonate bar. It messes up the layout, if you hide it it should be good.

**Comment by mgax** [comment]
> That's because of the impersonate bar. It messes up the layout, if you hide it it should be good.

Confirmed, that fixes the layout ✔️

**Comment by alexkiro** [comment]
> > That's because of the impersonate bar. It messes up the layout, if you hide it it should be good.
> 
> Confirmed, that fixes the layout

Yeah, for what is worth, I've been aware of the issue, as it breaks on other pages as well. I've just been putting off fixing it, since it's not impacting any users. Opened a ticket to at last have it tracked (https://github.com/ogorlab/ogor-frontend/issues/495)
