### ISSUE TITLE
Minor design changes to observation cards

### ISSUE THREAD

**Issue by ppscvalentin** [ogorlab/ogor-frontend#464]
- [x] background color and field boundary stroke color are different from mockups.
- [x] when pulling the most recent image we now show that image's date (e.g.: Jun 20). I would replace with "10 days [ago]". ~Screen only. Print or report is still "Jun 20".~
- [x] the flag that tells the image is resized can be hidden from regular users
- [x] NDVI value and icon are bigger now
- [x] Removed top & bottom gradient ~when card is selected~

**Comment by alexkiro** [comment]
> * Screen only. Print or report is still "Jun 20".

@ppscvalentin We don't have any print support in the app at the moment, I don't think we should introduce it randomly here.

**Comment by andreighh** [comment]
@ppscvalentin
> the flag that tells the image is resized can be hidden from regular users
Who are the regular users? Users without full access to a farm or users who are not admins?

**Comment by ppscvalentin** [comment]
> @ppscvalentin
> 
> > the flag that tells the image is resized can be hidden from regular users
> 
> Who are the regular users? Users without full access to a farm or users who are not admins?

Non-admin users

**Comment by alexkiro** [comment]
@andreighh I noticed an issue here, it seems the relative date is always shown at the moment. However it should only be shown if we are viewing the most recent raster available for a parcel. Examples places where this is wrongly shown:

 - parcel history view
 - parcel history tab in the map view 
 - compare pages

**Comment by ppscvalentin** [comment]
All good. Just noticed my bad wording here:

>  Removed top & bottom gradient when card is selected

meant to say:

>  Removed top & bottom gradient when card **completely**

Otherwise, all good!

**Comment by alexkiro** [comment]
> > Removed top & bottom gradient when card **completely**

@ppscvalentin changed and deployed
