### ISSUE TITLE
Login page / news section

### ISSUE THREAD

**Issue by dafinajeaca** [ogorlab/ogor-frontend#468]
**EN**

_Import_
You can add a new field from any KMZ/KML/SHP file that you have already saved on your computer.

_NDWI_
Interested to see the water stress level inside your crops? Just check the NDWI based maps for all of your fields.

_Demo farm_
Not sure that OGOR is suited for your needs? You can verify this by visiting the demo farm.

--------------------------------------
**RO**

_Import_
Poți adăuga un teren nou din orice fișier KMZ / KML / SHP pe care l-ați salvat deja pe computer.

_NDWI_
Vrei să vezi nivelul de stres hidric din interiorul culturilor tale? Verifică bărțile bazate pe NDWI.

_Demo farm_
Nu ești sigur că OGOR este potrivit pentru nevoile tale? Poți verifica acest lucru accesând ferma demo.

--------------------------------------
**FR**

_Importer_
Vous pouvez ajouter un nouveau champ à partir de n'importe quel fichier KMZ / KML / SHP que vous avez déjà enregistré sur votre ordinateur.

_NDWI_
Vous souhaitez connaître le niveau de stress hydrique à l'intérieur de vos cultures? Vérifiez simplement les cartes basées sur NDWI pour tous vos champs.

_Ferme de démonstration_
Vous n'êtes pas sûr que OGOR soit adapté à vos besoins? Vous pouvez le vérifier en visitant la ferme de démonstration.

**Comment by ppscvalentin** [comment]
My contribution - EMOJIs :D

🛰 Import

💧 NDWI

🎒 Demo farm
