### ISSUE TITLE
Add true color image in the map view observation details

### ISSUE THREAD

**Issue by alexkiro** [ogorlab/ogor-frontend#547]
While viewing the observation details in the map view we should also show the true color image (if available). 

 - [x] The image is overlapped over the map view and a transparent layer 
 - [x] The image is overlapped over the shape of the parcel 
 - [x] If available from the backend the image always appears whenever a parcel is selected 

---

See also https://github.com/ogorlab/non-tech/issues/122

**Comment by nico4** [comment]
We don't have True Color images on prod. (https://share.getcloudapp.com/9Zu8rBxK)
