### ISSUE TITLE
The shared farms are not displayed in the dropdown list, in the crop view.

### ISSUE THREAD

**Issue by dafinajeaca** [ogorlab/ogor-frontend#568]

**Comment by alexkiro** [comment]
Works for me :thinking: Do you have any other details that can help track this bug down? 

![Screenshot from 2021-03-01 08-17-09](https://user-images.githubusercontent.com/1538458/109458980-8d408200-7a66-11eb-8aac-a0e205313f1e.png)

**Comment by dafinajeaca** [comment]
Cannot reproduce anymore. Will be closed.
