### ISSUE TITLE
In grid view, we have entries with OVER_MAX_COVER flag.

### ISSUE THREAD

**Issue by dafinajeaca** [ogorlab/ogor-frontend#573]
![Screenshot_2021-02-15_105012](https://user-images.githubusercontent.com/52447572/107930093-32495e00-6f83-11eb-8714-6352965f20fa.jpg)

**Comment by alexkiro** [comment]
Can you please explain what's the bug here? 

Assuming you have the "Show skipped" checkbox selected, this is the intended behavior.

**Comment by dafinajeaca** [comment]
Cannot reproduce anymore. Bug will be closed.
