### ISSUE TITLE
Mobile.Missing image in field details view

### ISSUE THREAD

**Issue by dafinajeaca** [ogorlab/ogor-frontend#636]
1.Select a field with full cloud coverage (Alisa)
2.Open field details drawer
expected output: view NDVI/NDVI image
issue: the first entry to see is "Missing image"
proposal: do not display the "Missing image" and instead start the carousel of images with the latest available

**Comment by alexkiro** [comment]
This isn't really a bug, it's a part of the design cc @ppscvalentin ?

**Comment by ppscvalentin** [comment]
@dafinajeaca Field view should **show the same image as the one you clicked on** when you were on the Farm view. 

We cannot change the time cursor when drilling down from farm -> crop -> field. This issue will be resolved when and if we decide to show the latest available images on the farm view, no matter how old they are.
