### ISSUE TITLE
Add scroll indicator for date picker in Compare Parcels view

### ISSUE THREAD

**Issue by dafinajeaca** [ogorlab/ogor-frontend#78]
In the page for comparison between different fields, in the calendar on the left, you cannot see that you can scroll down/up in order to select older/newer dates.

![compare terenuri diferite](https://user-images.githubusercontent.com/52447572/81066472-d0cd6c80-8ee5-11ea-9d50-bb5944c6c575.png)

**Comment by alexkiro** [comment]
Page is getting a new design.
