### ISSUE TITLE
PROD.In the field evolution page, when switching between the seasons, the field cards flicker very nice. Like disco. :)

### ISSUE THREAD

**Issue by dafinajeaca** [ogorlab/ogor-frontend#79]
[Removed]

**Comment by alexkiro** [comment]
@dafinajeaca that's really strange, cannot reproduce at all. 

Can you let me know what browser (and version) you are using?

**Comment by dafinajeaca** [comment]
Google Chrome is up to date
Version 81.0.4044.129 (Official Build) (64-bit)
